#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lge/mh2lm

PRODUCT_COPY_FILES += \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Codec_cal.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/10_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/10_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/10_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/10_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/10_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/10_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/10_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/10_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/11_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/11_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/11_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/11_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/11_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/11_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/11_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/11_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/12_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/12_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/12_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/12_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/12_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/12_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/13_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/13_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/13_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/13_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/13_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/13_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/14_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/14_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/14_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/14_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/14_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/14_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/15_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/15_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/15_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/15_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/15_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/15_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/16_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/16_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/16_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/16_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/16_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/16_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/17_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/17_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/18_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/18_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/19_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/19_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/1_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/1_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/1_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/1_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/1_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/1_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/1_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/1_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/20_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/20_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/21_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/21_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/2_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/2_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/2_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/2_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/2_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/2_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/2_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/2_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/3_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/3_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/3_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/3_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/3_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/3_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/3_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/3_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/4_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/4_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/4_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/4_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/4_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/4_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/4_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/4_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/5_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/5_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/5_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/5_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/5_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/5_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/5_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/5_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/6_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/6_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/6_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/6_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/6_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/6_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/6_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/6_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/7_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/7_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/7_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/7_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/7_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/7_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/7_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/7_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/8_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/8_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/8_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/8_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/8_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/8_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/8_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/8_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/9_cine-max.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/9_cine-max.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/9_cine-min.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/9_cine-min.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/9_cine_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/9_cine_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/9_vignette.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/9_vignette.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/cinema/cine_min_10.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cinema/cine_min_10.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/0_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/0_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/10_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/10_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/1_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/1_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/2_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/2_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/3_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/3_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/4_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/4_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/5_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/5_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/6_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/6_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/7_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/7_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/8_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/8_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/film/9_film.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/film/9_film.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/food/1_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/food/1_food.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/iqm/ai_checker_graph.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/iqm/ai_checker_graph.dlc \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/iqm/fc4_awb.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/iqm/fc4_awb.dlc \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Grooming_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Grooming_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Idol_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Idol_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Iu_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Iu_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Japanese_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Japanese_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Luxury_eye_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Luxury_eye_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Luxury_lip_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Luxury_lip_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Natural_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Natural_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Rose_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Rose_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Teen_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Teen_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/capture/Wedding_c.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/capture/Wedding_c.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Grooming_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Grooming_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Idol_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Idol_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Iu_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Iu_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Japanese_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Japanese_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Luxury_eye_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Luxury_eye_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Luxury_lip_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Luxury_lip_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Natural_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Natural_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Rose_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Rose_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Teen_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Teen_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/preview/Wedding_p.cng:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/preview/Wedding_p.cng \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_10_grooming_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_10_grooming_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_10_grooming_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_10_grooming_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_1_natural_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_1_natural_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_1_natural_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_1_natural_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_2_rose_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_2_rose_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_2_rose_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_2_rose_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_3_luxury_eyes_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_3_luxury_eyes_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_3_luxury_eyes_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_3_luxury_eyes_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_4_teen_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_4_teen_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_4_teen_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_4_teen_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_5_luxury_lip_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_5_luxury_lip_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_5_luxury_lip_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_5_luxury_lip_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_6_idol_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_6_idol_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_6_idol_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_6_idol_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_7_wedding_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_7_wedding_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_7_wedding_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_7_wedding_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_8_iu_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_8_iu_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_8_iu_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_8_iu_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_9_japanese_h_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_9_japanese_h_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/makeup/shadowlight/LG_9_japanese_s_325x400.BGR32:$(TARGET_COPY_OUT_VENDOR)/etc/camera/makeup/shadowlight/LG_9_japanese_s_325x400.BGR32 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/outfocus/deepportrait_snapshot.dlce:$(TARGET_COPY_OUT_VENDOR)/etc/camera/outfocus/deepportrait_snapshot.dlce \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/portraitlight/Back_filter.NV21:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portraitlight/Back_filter.NV21 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/portraitlight/Gradation.NV21:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portraitlight/Gradation.NV21 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/portraitlight/Pink.NV21:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portraitlight/Pink.NV21 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/portraitlight/Texture.NV21:$(TARGET_COPY_OUT_VENDOR)/etc/camera/portraitlight/Texture.NV21 \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/1_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/1_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/2_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/2_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/3_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/3_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/4_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/4_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/5_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/5_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/6_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/6_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/7_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/7_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/8_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/8_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/selfie/9_selfie.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/selfie/9_selfie.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/0_smartcam.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/0_smartcam.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/10_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/10_smartcam_food.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/11_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/11_smartcam_food.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/12_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/12_smartcam_food.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/13_1_H_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/13_1_H_smartcam_person_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/13_2_L_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/13_2_L_smartcam_person_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/13_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/13_smartcam_person_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/14_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/14_smartcam_person_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/15_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/15_smartcam_person_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/16_smartcam_person_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/16_smartcam_person_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/17_1_H_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/17_1_H_smartcam_landscape.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/17_2_L_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/17_2_L_smartcam_landscape.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/17_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/17_smartcam_landscape.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/18_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/18_smartcam_landscape.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/19_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/19_smartcam_landscape.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/1_1_H_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/1_1_H_smartcam_pet.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/1_2_L_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/1_2_L_smartcam_pet.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/1_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/1_smartcam_pet.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/20_smartcam_landscape.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/20_smartcam_landscape.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/21_1_H_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/21_1_H_smartcam_sunset_sunrise.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/21_2_L_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/21_2_L_smartcam_sunset_sunrise.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/21_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/21_smartcam_sunset_sunrise.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/22_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/22_smartcam_sunset_sunrise.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/23_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/23_smartcam_sunset_sunrise.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/24_smartcam_sunset_sunrise.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/24_smartcam_sunset_sunrise.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/25_smartcam_flower.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/25_smartcam_flower.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/26_smartcam_flower.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/26_smartcam_flower.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/27_smartcam_flower.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/27_smartcam_flower.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/28_smartcam_flower.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/28_smartcam_flower.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/29_1_H_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/29_1_H_smartcam_people_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/29_2_L_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/29_2_L_smartcam_people_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/29_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/29_smartcam_people_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/2_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/2_smartcam_pet.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/30_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/30_smartcam_people_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/31_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/31_smartcam_people_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/32_smartcam_people_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/32_smartcam_people_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/33_1_H_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/33_1_H_smartcam_baby_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/33_2_L_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/33_2_L_smartcam_baby_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/33_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/33_smartcam_baby_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/34_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/34_smartcam_baby_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/35_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/35_smartcam_baby_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/36_smartcam_baby_rear.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/36_smartcam_baby_rear.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/37_smartcam_animal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/37_smartcam_animal.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/38_smartcam_animal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/38_smartcam_animal.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/39_smartcam_animal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/39_smartcam_animal.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/3_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/3_smartcam_pet.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/40_smartcam_animal.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/40_smartcam_animal.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/41_1_H_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/41_1_H_smartcam_beverage.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/41_2_L_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/41_2_L_smartcam_beverage.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/41_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/41_smartcam_beverage.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/42_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/42_smartcam_beverage.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/43_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/43_smartcam_beverage.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/44_smartcam_beverage.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/44_smartcam_beverage.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/45_smartcam_fruit.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/45_smartcam_fruit.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/46_smartcam_fruit.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/46_smartcam_fruit.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/47_smartcam_fruit.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/47_smartcam_fruit.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/48_smartcam_fruit.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/48_smartcam_fruit.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/49_smartcam_snow.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/49_smartcam_snow.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/4_smartcam_pet.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/4_smartcam_pet.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/50_smartcam_snow.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/50_smartcam_snow.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/51_smartcam_snow.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/51_smartcam_snow.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/52_smartcam_snow.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/52_smartcam_snow.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/53_1_H_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/53_1_H_smartcam_sky.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/53_2_L_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/53_2_L_smartcam_sky.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/53_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/53_smartcam_sky.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/54_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/54_smartcam_sky.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/55_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/55_smartcam_sky.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/56_smartcam_sky.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/56_smartcam_sky.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/57_smartcam_beach.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/57_smartcam_beach.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/58_smartcam_beach.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/58_smartcam_beach.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/59_smartcam_beach.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/59_smartcam_beach.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/5_1_H_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/5_1_H_smartcam_city.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/5_2_L_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/5_2_L_smartcam_city.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/5_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/5_smartcam_city.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/60_smartcam_beach.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/60_smartcam_beach.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/61_smartcam_lowlight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/61_smartcam_lowlight.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/62_smartcam_lowlight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/62_smartcam_lowlight.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/63_smartcam_lowlight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/63_smartcam_lowlight.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/64_smartcam_lowlight.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/64_smartcam_lowlight.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/65_1_H_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/65_1_H_smartcam_person_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/65_2_L_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/65_2_L_smartcam_person_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/65_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/65_smartcam_person_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/66_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/66_smartcam_person_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/67_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/67_smartcam_person_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/68_smartcam_person_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/68_smartcam_person_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/69_1_H_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/69_1_H_smartcam_people_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/69_2_L_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/69_2_L_smartcam_people_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/69_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/69_smartcam_people_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/6_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/6_smartcam_city.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/70_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/70_smartcam_people_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/71_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/71_smartcam_people_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/72_smartcam_people_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/72_smartcam_people_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/73_1_H_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/73_1_H_smartcam_baby_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/73_2_L_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/73_2_L_smartcam_baby_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/73_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/73_smartcam_baby_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/74_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/74_smartcam_baby_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/75_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/75_smartcam_baby_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/76_smartcam_baby_front.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/76_smartcam_baby_front.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/7_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/7_smartcam_city.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/8_smartcam_city.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/8_smartcam_city.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/91_smartcam_basic_01.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/91_smartcam_basic_01.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/92_smartcam_basic_02.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/92_smartcam_basic_02.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/93_smartcam_basic_03.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/93_smartcam_basic_03.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/94_smartcam_basic_04.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/94_smartcam_basic_04.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/9_1_H_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/9_1_H_smartcam_food.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/9_2_L_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/9_2_L_smartcam_food.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/smartcam/9_smartcam_food.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/smartcam/9_smartcam_food.dat \
    vendor/lge/mh2lm/proprietary/vendor/etc/camera/vnr/SJ_VideoNR_LUT.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vnr/SJ_VideoNR_LUT.bin \
    vendor/lge/mh2lm/proprietary/vendor/etc/gnss_antenna_info.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gnss_antenna_info.conf \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Dual_Sharp_WQHD_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_Sharp_WQHD_cmd_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Dual_Sharp_wqhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_Sharp_wqhd_video_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Dual_nt35597_cmd_mode_dsi_truly_panel_without_DSC.xml.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_nt35597_cmd_mode_dsi_truly_panel_without_DSC.xml.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Dual_nt35597_video_mode_dsi_truly_panel_without_DSC.xml.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_nt35597_video_mode_dsi_truly_panel_without_DSC.xml.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Dual_nt36850_cmd_mode_dsi_truly_panel_without_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_nt36850_cmd_mode_dsi_truly_panel_without_DSC.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Dual_s6e3ha3_amoled_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_s6e3ha3_amoled_cmd_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_R66456_MD_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_R66456_MD_cmd_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Sharp_2k_cmd_mode_qsync_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_2k_cmd_mode_qsync_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Sharp_2k_video_mode_qsync_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_2k_video_mode_qsync_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Sharp_4k_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_4k_cmd_mode_dsc_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Sharp_4k_video_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_4k_video_mode_dsc_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Sharp_fhd_cmd_mode_qsync_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_fhd_cmd_mode_qsync_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_Sharp_fhd_video_mode_qsync_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_fhd_video_mode_qsync_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_hx83112a_video_mode_dsi_truly_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_hx83112a_video_mode_dsi_truly_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_nt35597_cmd_mode_dsi_truly_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35597_cmd_mode_dsi_truly_panel_with_DSC.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_nt35597_video_mode_dsi_truly_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35597_video_mode_dsi_truly_panel_with_DSC.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_nt35695b_truly_fhd_command_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35695b_truly_fhd_command_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_nt35695b_truly_fhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35695b_truly_fhd_video_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_nt36672_truly_fhd_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt36672_truly_fhd_video_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_nt36672c_fhd_plus_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt36672c_fhd_plus_video_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_rm69298_amoled_fhd+_cmd_mode_dsi_truly_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_rm69298_amoled_fhd+_cmd_mode_dsi_truly_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_rm69298_amoled_fhd+_video_mode_dsi_truly_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_rm69298_amoled_fhd+_video_mode_dsi_truly_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_rm69299_amoled_fhd+_cmd_mode_dsi_visionox_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_rm69299_amoled_fhd+_cmd_mode_dsi_visionox_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_rm69299_amoled_fhd+_video_mode_dsi_visionox_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_rm69299_amoled_fhd+_video_mode_dsi_visionox_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_sharp_1080p_120hz_dual_dsi_cmd_mode_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_sharp_1080p_120hz_dual_dsi_cmd_mode_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_sharp_1080p_cmd_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_sharp_1080p_cmd_mode_dsi_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_sw43404_amoled_boe_fhd+_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_sw43404_amoled_boe_fhd+_panel_with_DSC.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_sw43404_amoled_cmd_mode_dsi_boe_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_sw43404_amoled_cmd_mode_dsi_boe_panel_with_DSC.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_sw43404_amoled_video_mode_dsi_boe_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_sw43404_amoled_video_mode_dsi_boe_panel_with_DSC.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_td4328_cmd_mode_dsi_truly_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_td4328_cmd_mode_dsi_truly_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_td4328_video_mode_dsi_truly_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_td4328_video_mode_dsi_truly_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_td4330_cmd_mode_dsi_truly_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_td4330_cmd_mode_dsi_truly_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/qdcm_calib_data_td4330_video_mode_dsi_truly_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_td4330_video_mode_dsi_truly_panel.xml \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/descriptor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/descriptor.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/nanopb.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/nanopb.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_accel.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_accel.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_accel_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_accel_cal.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_activity_recognition.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_activity_recognition.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_ambient_light.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ambient_light.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_ambient_temperature.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ambient_temperature.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_amd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_amd.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_aont.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_aont.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_basic_gestures.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_basic_gestures.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_bring_to_ear.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_bring_to_ear.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_cal.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_client.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_client.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_cmc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_cmc.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_da_test.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_da_test.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_device_mode.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_device_mode.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_device_orient.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_device_orient.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_diag.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_diag.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_diag_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_diag_sensor.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_direct_channel.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_direct_channel.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_dpc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_dpc.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_ext_svc.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ext_svc.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_facing.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_facing.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_fmv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_fmv.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_formatter.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_formatter.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_fw.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_fw.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_game_rv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_game_rv.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_geomag_rv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_geomag_rv.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_gravity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gravity.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_gyro.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_gyro_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro_cal.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_gyro_rot_matrix.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_gyro_rot_matrix.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_hall.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_hall.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_heart_beat.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_heart_beat.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_heart_rate.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_heart_rate.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_hinge_angle.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_hinge_angle.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_humidity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_humidity.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_knock_on_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_knock_on_proximity.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_lg_airtouch_wakeup_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_airtouch_wakeup_proximity.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_lg_filtered_pressure.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_filtered_pressure.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_lg_gated_gyro.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_gated_gyro.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_lg_health_activity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_health_activity.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_lg_pam.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_pam.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_lg_tof_wakeup_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lg_tof_wakeup_proximity.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_lgpickup.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_lgpickup.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_mag.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_mag.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_mag_cal.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_mag_cal.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_motion_accel.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_motion_accel.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_oem1.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_oem1.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_offbody_detect.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_offbody_detect.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_pd_algo.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pd_algo.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_pedometer.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pedometer.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_pedometer_wrist.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pedometer_wrist.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_physical_sensor_test.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_physical_sensor_test.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_pose_6dof.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pose_6dof.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_ppg.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ppg.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_pressure.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_pressure.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_proximity.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_psmd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_psmd.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_registry.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_registry.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_resampler.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_resampler.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_rgb.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rgb.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_rmd.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rmd.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_rotv.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_rotv.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_sar.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sar.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_sensor_temperature.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sensor_temperature.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_sig_motion.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_sig_motion.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_std.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_std_event_gated_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_event_gated_sensor.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_std_sensor.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_sensor.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_std_type.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_std_type.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_step_detect.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_step_detect.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_suid.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_suid.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_thermopile.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_thermopile.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_thresh.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_thresh.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_threshold.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_threshold.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_tilt.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_tilt.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_tilt_to_wake.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_tilt_to_wake.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_ultra_violet.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_ultra_violet.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_virtual_proximity.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_virtual_proximity.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_wakeup_light.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_wakeup_light.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/proto/sns_wrist_tilt_gesture.proto:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/proto/sns_wrist_tilt_gesture.proto \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/ak991x_dri_0.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/apds9169.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9169.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/apds9169_D_cut.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/apds9169_D_cut.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/icm4x6xx_0.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sm8150_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sm8150_ak991x_0.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sm8150_apds9169.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sm8150_apds9169.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sm8150_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sm8150_icm4x6xx_0.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sm8150_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sm8150_power_0.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sm8150_spl06_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sm8150_spl06_0.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_disabled.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_amd_sw_enabled.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_aont.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_basic_gestures.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_bring_to_ear.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_ccd.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_cm.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_dae.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_device_orient.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_diag_filter.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_distance_bound.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_dpc.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_facing.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_fmv.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_geomag_rv.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_gyro_cal.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_lg_filtered_pressure.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_lg_filtered_pressure.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_lg_gated_gyro.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_lg_gated_gyro.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_mag_cal.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_multishake.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_pedometer.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rmd.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_rotv.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_smd.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_disabled.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_sw_enabled.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_tilt_to_wake.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_window_orientation.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_window_orientation.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/sns_wrist_pedo.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/config/spl06_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/config/spl06_0.json \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/registry/sensors_registry:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_registry \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/registry/registry/sensors_settings:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/registry/registry/sensors_settings \
    vendor/lge/mh2lm/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/lge/mh2lm/proprietary/vendor/etc/thermal-engine-8150.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-8150.conf \
    vendor/lge/mh2lm/proprietary/vendor/etc/wifi/GLOBAL/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan.bin \
    vendor/lge/mh2lm/proprietary/vendor/etc/wifi/GLOBAL/bdwlan_ch0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan_ch0.bin \
    vendor/lge/mh2lm/proprietary/vendor/etc/wifi/GLOBAL/bdwlan_ch1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/GLOBAL/bdwlan_ch1.bin \
    vendor/lge/mh2lm/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/lge/mh2lm/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/lge/mh2lm/proprietary/vendor/etc/wifi/icudt53l.dat:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/icudt53l.dat \
    vendor/lge/mh2lm/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/lge/mh2lm/proprietary/vendor/firmware/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw21.tlv \
    vendor/lge/mh2lm/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB0-dsp1-l-cal.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB0-dsp1-l-cal.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB0-dsp1-l-cal.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB0-dsp1-l-cal.wmfw \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB0-dsp1-l-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB0-dsp1-l-prot.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB0-dsp1-l-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB0-dsp1-l-prot.wmfw \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB0-dsp1-r-cal.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB0-dsp1-r-cal.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB0-dsp1-r-cal.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB0-dsp1-r-cal.wmfw \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB0-dsp1-r-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB0-dsp1-r-prot.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB0-dsp1-r-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB0-dsp1-r-prot.wmfw \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB2-dsp1-l-cal.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB2-dsp1-l-cal.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB2-dsp1-l-cal.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB2-dsp1-l-cal.wmfw \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB2-dsp1-l-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB2-dsp1-l-prot.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB2-dsp1-l-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB2-dsp1-l-prot.wmfw \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB2-dsp1-r-cal.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB2-dsp1-r-cal.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB2-dsp1-r-cal.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB2-dsp1-r-cal.wmfw \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB2-dsp1-r-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB2-dsp1-r-prot.bin \
    vendor/lge/mh2lm/proprietary/vendor/firmware/cs35l41-revB2-dsp1-r-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-revB2-dsp1-r-prot.wmfw \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_uc.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_uc.b00 \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_uc.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_uc.b01 \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_uc.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_uc.b02 \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_uc.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_uc.elf \
    vendor/lge/mh2lm/proprietary/vendor/firmware/ipa_uc.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_uc.mdt \
    vendor/lge/mh2lm/proprietary/vendor/firmware/rcv_bypass_off.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/rcv_bypass_off.txt \
    vendor/lge/mh2lm/proprietary/vendor/firmware/rcv_bypass_on.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/rcv_bypass_on.txt \
    vendor/lge/mh2lm/proprietary/vendor/firmware/spk_bypass_off.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk_bypass_off.txt \
    vendor/lge/mh2lm/proprietary/vendor/firmware/spk_bypass_on.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk_bypass_on.txt \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.sensormodule.imx363.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.imx363.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.sensormodule.s5k3m3.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.s5k3m3.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.sensormodule.s5kgd1_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.s5kgd1_front.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.sensormodule.s5kgd1_multicam.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.s5kgd1_multicam.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.tuned.imx363_mh2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.imx363_mh2.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.tuned.s5k3m3_mh2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.s5k3m3_mh2.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.tuned.s5kgd1_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.s5kgd1_front.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/com.qti.tuned.s5kgd1_multicam.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.s5kgd1_multicam.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/lge/mh2lm/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin

PRODUCT_PACKAGES += \
    sensors.ssc \
    libpn553_fw \
    com.qti.eeprom.imx363_fm24c64d \
    com.qti.eeprom.s5k3m3_fm24c64d \
    com.qti.eeprom.s5kgd1_fm24c64d \
    com.qti.eeprom.s5kgd1_fm24c64d_multicam \
    com.qti.sensor.imx363 \
    com.qti.sensor.s5k3m3 \
    com.qti.sensor.s5kgd1_front \
    com.qti.sensor.s5kgd1_multicam \
    com.lge.node.camerasolution \
    com.lge.node.capturebokeh \
    com.lge.node.dupis \
    com.lge.node.duvis \
    com.lge.node.elpis \
    com.lge.node.elvis \
    com.lge.node.hdr \
    com.lge.node.lavis \
    com.lge.node.multiframe \
    com.lge.node.realtimebokeh \
    com.lge.node.tofcapb \
    com.lge.node.tofrtb \
    com.lge.stats.aec \
    com.lge.stats.aecwrapper \
    com.lge.stats.af \
    com.lge.stats.af_core \
    com.lge.stats.awb \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.depth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libdepthmapwrapper \
    libdepthmapwrapper_secure \
    libtofcapb \
    libtofrtb \
    liblg_aec_param_imx363_binning_preview \
    liblg_aec_param_imx363_binning_video \
    liblg_aec_param_imx363_cine_video \
    liblg_aec_param_imx363_hfr_120 \
    liblg_aec_param_imx363_hfr_240 \
    liblg_aec_param_imx363_hfr_60 \
    liblg_aec_param_imx363_night_preview \
    liblg_aec_param_imx363_out_focus \
    liblg_aec_param_imx363_out_focus_video \
    liblg_aec_param_imx363_panorama \
    liblg_aec_param_imx363_preview \
    liblg_aec_param_imx363_sensor_hdr_auto_preview \
    liblg_aec_param_imx363_sensor_hdr_auto_video \
    liblg_aec_param_imx363_sensor_hdr_on_preview \
    liblg_aec_param_imx363_sensor_hdr_on_video \
    liblg_aec_param_imx363_video \
    liblg_aec_param_s5k3m3_binning_preview \
    liblg_aec_param_s5k3m3_binning_video \
    liblg_aec_param_s5k3m3_cine_video \
    liblg_aec_param_s5k3m3_hfr_120 \
    liblg_aec_param_s5k3m3_hfr_240 \
    liblg_aec_param_s5k3m3_hfr_60 \
    liblg_aec_param_s5k3m3_night_preview \
    liblg_aec_param_s5k3m3_out_focus \
    liblg_aec_param_s5k3m3_out_focus_video \
    liblg_aec_param_s5k3m3_panorama \
    liblg_aec_param_s5k3m3_preview \
    liblg_aec_param_s5k3m3_sensor_hdr_auto_preview \
    liblg_aec_param_s5k3m3_sensor_hdr_auto_video \
    liblg_aec_param_s5k3m3_sensor_hdr_on_preview \
    liblg_aec_param_s5k3m3_sensor_hdr_on_video \
    liblg_aec_param_s5k3m3_video \
    liblg_awb_param_imx363n2_preview \
    liblg_awb_param_imx363n2_video \
    liblg_awb_param_imx363n_preview \
    liblg_awb_param_imx363n_video \
    liblg_awb_param_imx363nb_preview \
    liblg_awb_param_imx363nb_video \
    liblg_awb_param_s5k3m3w2_preview \
    liblg_awb_param_s5k3m3w2_video \
    liblg_awb_param_s5k3m3wb_preview \
    liblg_awb_param_s5k3m3wb_video \
    liblg_awb_param_s5k3m5t_preview \
    liblg_awb_param_s5k3m5t_video \
    liblg_awb_param_s5k3m5tb_preview \
    liblg_awb_param_s5k3m5tb_video \
    sensors.hal.flicker \
    camera.msmnile \
    com.qti.chi.override \
    fingerprint.msmnile \
    lib.com.lge.elvis \
    libAutoContrast \
    libCmcPdaf \
    libCmcPdaf_tele \
    libRbsFlow \
    libSJVideoNR \
    libSNPE \
    libSRIyuv \
    libarcsoft_beauty_picselfie \
    libarcsoft_depth_bokeh_img \
    libarcsoft_depthcam_portrait_lighting \
    libarcsoft_dualcam_portraitlighting \
    libarcsoft_dualcam_refocus \
    libarcsoft_dualcam_refocus_front \
    libarcsoft_dualcam_refocus_rear_t \
    libarcsoft_makeup \
    libarcsoft_object_tracking \
    libarcsoft_picselfie_algorithm \
    libarcsoft_singlecam_portrait_lighting \
    libbwfocuspeaking \
    libc++_shared \
    libcamera_nn_stub \
    libcamxfdalgov7 \
    libcamxfdalgov8 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcinemaeffect \
    libcom.qti.chinodeutils \
    libdepthcomputation_wrapper \
    libets_teeclient_v2 \
    libfilm_emulation \
    libfilm_emulation_symphony \
    libfpsph \
    liblgae_main \
    liblgawb_main \
    liblgdnnsnpe \
    liblghdri \
    liblgsnpeawb \
    liblgsnpeawb_beta \
    libmorpho_image_stab31 \
    libmorpho_wdr2 \
    libmpbase \
    libpn553_fw_64 \
    libspectre3 \
    libsymphony-1.1.4 \
    libsymphony-cpu \
    libsymphonypower-1.1.4 \
    libsymphonypower \
    sensors.sar \
    vendor.lge.hardware.sensors@1.0 \
    AlacDecoderModule.so \
    ApeDecoderModule.so \
    AudioContextDetection.so \
    AudioSphereModule.so \
    CFCMModule.so \
    EtsiAmrWbPlusDecModule.so \
    EtsiEaacPlusEncAndCmnModule.so \
    FlacDecoderModule.so \
    HeaacDecoderModule.so \
    LdacModule.so \
    SAPlusCmnModule.so \
    SVACmnModule.so \
    VoiceWakeup_V2_Module.so \
    VorbisDecoderModule.so \
    WmaProDecoderModule.so \
    WmaStdDecoderModule.so \
    activity \
    capi_v2_aptX_Classic \
    capi_v2_aptX_HD \
    cellinfo_tools \
    chre_drv_bt \
    chre_drv_gf \
    chre_drv_loc \
    chre_drv_modem \
    chre_drv_wifi \
    chre_pal \
    fastrpc_shell_0 \
    ffns_module_fv9.so \
    ffv_module.so \
    ffv_module_fv9.so \
    fluence_bs_module.so \
    fluence_bs_module_fv9.so \
    fluence_ef_module.so \
    fluence_ef_module_fv9.so \
    fluence_pro_vc_module.so \
    fluence_pro_vc_module_fv9.so \
    fluence_pro_vr_module.so \
    fluence_pro_vr_module_fv9.so \
    fluence_sm_module.so \
    fluence_sm_module_fv9.so \
    fluence_voiceplus_module.so \
    geofence \
    lg_nanoapp_pa \
    lg_nanoapp_sbd \
    lg_nanoapp_su \
    libVC1Dec \
    libVC1DecDsp_skel \
    libapps_mem_heap \
    libarcsoft_dualcam_refocus_skel \
    libcamera_nn_skel \
    libchre_slpi_skel \
    libcvpdsp_skel \
    libdspCV_skel \
    libdsp_streamer_add_constant \
    libdsp_streamer_binning \
    libdsp_streamer_skel \
    libfastcvadsp \
    libfastcvdsp_skel \
    libhexagon_nn_skel \
    libqdepth_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsns_device_mode_skel \
    libsns_low_lat_stream_skel \
    libstabilitydomain_skel \
    libsysmon_skel \
    libsysmondomain_skel \
    libsysmonquery_skel \
    lowi_client \
    mm_fluence_sb_module.so \
    mmecns_module.so \
    sm_fluence_sb_module.so \
    smecns_v2_module.so \
    smecns_v2_module_fv9.so

PRODUCT_PACKAGES += \
    vendor_firmware_wlan_qca_cld_bdwlan_bin \
    vendor_firmware_wlan_qca_cld_bdwlan_ch0_bin \
    vendor_firmware_wlan_qca_cld_bdwlan_ch1_bin
